[build]
command = "curl -sL https://github.com/gohugoio/hugo/releases/download/v0.42/hugo_0.42_Linux-64bit.tar.gz | tar xz && ./hugo"
publish = "public"

[context]
[context.branch-deploy]
command = "curl -sL https://github.com/gohugoio/hugo/releases/download/v0.42/hugo_0.42_Linux-64bit.tar.gz | tar xz && ./hugo -F -b $DEPLOY_PRIME_URL"
[context.deploy-preview]
command = "curl -sL https://github.com/gohugoio/hugo/releases/download/v0.42/hugo_0.42_Linux-64bit.tar.gz | tar xz && ./hugo -F -b $DEPLOY_PRIME_URL"
[context.production]
[context.production.environment]
HUGO_ENV = "production"
