---
title: compare slopes in linear regression
author: Ming Tang
date: '2020-10-02'
slug: compare-slopes-in-linear-regression
categories:
  - statistics
  - rstats
tags:
  - statistics
  - rstats
  - linear-regresssion
header:
  caption: ''
  image: ''
  preview: yes
editor_options: 
  chunk_output_type: console
---



<p>I asked this question on <a href="https://twitter.com/tangming2005/status/1308225162324647937">twitter</a>.</p>
<div id="load-the-package" class="section level3">
<h3>load the package</h3>
<pre class="r"><code>library(tidyverse)</code></pre>
</div>
<div id="make-some-dummy-data" class="section level3">
<h3>make some dummy data</h3>
<p>The dummy example: We have two groups of samples: disease and health.
We treat those cells in vitro with different dosages (0, 1, 5) of a chemical X and count the cell number after 3 hours.</p>
<pre class="r"><code>x &lt;- tibble(
  &#39;0&#39; = c(8.66,
               11.50,
               7.01,
               13.40,
               11.30,
               8.13,
               5.92,
               7.54),
  &#39;1&#39; = c(22.10,
               23.00,
               22.00,
               35.70,
               32.60,
               26.90,
               23.30,
               21.60),
  &#39;5&#39; = c(31.20,
               30.60,
               28.40,
               37.30,
               41.40,
               40.20,
               29.20,
               35.40))

y &lt;- tibble(
  &#39;0&#39; = c(13.90,
               5.67,
               2.59,
               9.77,
               5.63,
               4.59,
               7.35,
               5.92),
  &#39;1&#39; = c(12.60,
               8.48,
               5.59,
               5.43,
               13.10,
               18.00,
               23.90,
               14.50),
  &#39;5&#39; = c(20.00,
               10.70,
               9.73,
               16.20,
               15.10,
               21.30,
               25.60,
               18.40))

x&lt;- x %&gt;% tidyr::gather(1:3, key= &quot;dose&quot;, value = &quot;cells&quot;) %&gt;%
  mutate(group = &quot;Health&quot;)

y&lt;- y %&gt;% tidyr::gather(1:3, key= &quot;dose&quot;, value = &quot;cells&quot;) %&gt;%
  mutate(group = &quot;Disease&quot;)

z&lt;- rbind(x,y)

ggplot(z, aes(x= dose, y = cells)) +
  geom_boxplot(aes(color = dose)) +
  geom_point() +
  facet_wrap(~group) +
  theme_bw(base_size = 14)</code></pre>
<p><img src="/post/2020-10-02-compare-slopes-in-linear-regression.en_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>We see that as the dosage increases, the cell number increases in both disease and healthy groups.
However, the question is that if the cell number increases faster in the healthy group than the disease group or not? How can I get a p-value for that?</p>
<p>As <a href="https://twitter.com/ChenxinLi2/status/1308232791709024257">Chenxin Li</a> pointed out. The dose has to be <code>numeric</code>:</p>
<pre class="r"><code>z&lt;- z %&gt;%
  mutate(dose = as.numeric(dose)) 

lm_res&lt;- lm(cells ~  dose *group, data = z)
summary(lm_res)</code></pre>
<pre><code>## 
## Call:
## lm(formula = cells ~ dose * group, data = z)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -8.839 -4.918 -1.357  3.801 16.771 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)        8.7048     1.7367   5.012 9.26e-06 ***
## dose               1.7737     0.5899   3.007  0.00435 ** 
## groupHealth        6.0546     2.4560   2.465  0.01766 *  
## dose:groupHealth   2.3958     0.8343   2.872  0.00626 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.243 on 44 degrees of freedom
## Multiple R-squared:  0.6839, Adjusted R-squared:  0.6624 
## F-statistic: 31.74 on 3 and 44 DF,  p-value: 4.443e-11</code></pre>
</div>
<div id="interpret-the-result" class="section level3">
<h3>Interpret the result</h3>
<p><span class="math inline">\(beta 0 = 8.7\)</span> is the intercept.<br />
<span class="math inline">\(beta 1 = 1.77\)</span> is the coefficient of the <code>dose</code>.<br />
<span class="math inline">\(beta 2 = 6.05\)</span> is the coefficient of the <code>group</code>.<br />
<span class="math inline">\(beta 3 = 2.39\)</span> is the coefficient of the interaction term <code>dose:group</code>. <span class="math inline">\(beta3\)</span> is the <strong>difference</strong> in the slopes of non-reference minus reference (reference is the Disease group chosen by R alphabetically).</p>
<p>In other words, the slope of Healthy group - Disease group = 2.39, which means the cell number in the healthy group increases faster. The p-value is 0.00626</p>
<p>I want to thank Collin in Shirley’s lab and other tweeps for helping out for my question.</p>
<p>I found <a href="https://www.theanalysisfactor.com/interpreting-interactions-in-regression/">this explanation</a> of how to inteprete the interaction term is very good. I highly recommend reading through this as well: <a href="https://lindeloev.github.io/tests-as-linear/#62_two-way_anova_(plot_in_progress)" class="uri">https://lindeloev.github.io/tests-as-linear/#62_two-way_anova_(plot_in_progress)</a></p>
</div>
