---
title: "Review 2024"
author: Ming Tommy Tang
date: "2025-01-01"
slug: review-2024
categories:
  - review
tags:
  - bioinformatics
  - education
  - data
header:
  caption: ''
  image: ''
editor_options: 
  chunk_output_type: console
---

As 2024 wraps up, it's the perfect time to reflect and prepare for the new year. 
I wrote the review for 2023 [here](https://divingintogeneticsandgenomics.com/post/review-2023/).

### Goals reached

1. ✅ I lost 12 lb in 6 weeks! 

2. ✅ Supported the clinical trial to identify bio markers for potential responders to our drug at Immunitas. Helped with indication selection for the second and third program. I moved to Astrazeneca in August. I really appreciate my experience at Immunitas and learned a lot. Now I want to learn more at AstraZeneca! 

3. ✅ Go to one conference that is not local. (I am spoiled to attend many conferences in Boston last year). I went to EMBL for https://biont-training.eu/CarpentryConnect2024.html conference at Heidelberg, Germany. This is my first time traveling to Europe. Thanks again for the invitation! 

4. ❌  I did not Host another AI for drug discovery conference in 2024. I co-organized this one in 2023.

5. ❌ I did not Finish this deep learning course https://course.fast.ai/. This will be in 2025.

6. ✅ Take one more leadership training session. I took a  [Red10 leadership session ](https://www.red10dev.com/) for influence at AstraZeneca. It is a great program and I will post some notes on Saturdays.

7. ✅ Make at least one video a week; one blog post/tutorial (42 posts in 2024)every two weeks. 7.5K subscribers after 1.5 years! https://www.youtube.com/@chatomics/videos

8. ✅ Post every day on Linkedin pre-scheduled with http://buffer.com

9. ✅ Write 500 words every day. (either my learning from podcasts on my commute or any reading)

10. ✅ Read at least 12 books again!  Some of them: 

* The Motive by Patrick Lencioni

* Trillion Dollar coach by Eric Schmidt, Jonathan Rosenberg and Alan Eagle.

* The Alchemist by Paulo Coelho.

* The War of Art by Steven Pressfield

* Never split the difference by Chris Voss

* The pychology of Money by Morgan Housel

* Tribes by Seth Godin

* Tools of Titans by Tim Ferris

* Crossing the chasm by Geoffery Moore

* Zero to one by Peter Thiel

* Building reproducible analytical pipelines with R by Bruno Rodrigues

* Software engineering for Data scientists by Catherine Nelson


### Goals in 2025 

New Year's resolutions are popular, but how much have you achieved? Consistency is the key. 

Consistency transforms actions into results.

When you prioritize your most important goal, break it down into daily tasks. Those consistent days turn into consistent weeks...

Consistent weeks lead to consistent months.

And consistent months create consistent years.

All of that builds an epic life.

- For me, my technical skill goal is to finish the deep learning course on Fast.ai https://course.fast.ai/. It was on my to-do last year, but I didn’t finish. Failure isn’t scary—it’s a chance to learn and keep moving forward.

- My goal for LinkedIn? Post long, high-quality content every day.

I batch schedule posts on Sundays:

• Mon-Fri/Sunday: Bioinformatics (technical)

• Sat: Leadership & management & life lessons

- For self-improvement, I keep a daily reflection diary.It’s been 2 years, and my goal is to continue this habit every day. It helps me grow.

- In management, my focus is building trust with my team. I aim to support their growth—both technically and with soft skills.

- At work, my single goal is to deliver portfolio support analysis on time and consistently drive the project to have novel biological insights.

- Read another 12 books!

I wish you all a prosperous 2025! 
